@startuml
---
description:
author: Wesley Benvindo
release:
license:
version: 1.0.0
---
!include<archimate/Archimate>

title
    Diagrama de Atividade
    Emissão de relatórios (Administradores)
end title

caption
Desenvolvido por
Wesley Benvidno -RU: 4596063
end caption

!theme carbon-gray


start
:Loga no sistema com uma conta de adminstrador;
:Navega até a página onde pode fazer a gestão de relatório;
:Seleciona emitir novo relatório;
:Seleciona o tipo e os dados que irão compor este relaórios;
note
Aqui pode ser selecionado por exemplo:
Equipe e relacionar as horas mensais de trabalho,
Ou ainda as internações e relacionar com
as datas de maior e menor demanda;
end note
if (Há modelos disponíves?) then (Sim)
    if(Seleciona modelo?) then (Sim)
    :Aplica o modelo de exportação;
    else
        :Seleciona o formato de saída (csv, xlsx);
    end if
    else
    :Seleciona o formato de saída (csv, xlsx);
end if
    :Exporta os dados sem aplicar modelo;

stop

@enduml
