@startuml
---
description:
author: Wesley Benvindo
release:
license:
version: 1.0.0
---
!include<archimate/Archimate>

'header: Casos de uso geral

title
    Diagrama de Caso
    Relatórios
end title

caption
Desenvolvido por
Wesley Benvidno -RU: 4596063
end caption

!theme carbon-gray
skinparam actorStyle awesome

'actor #a7a6ba Paciente <<User>> as pc
actor #5e716a System <<System>> as sys
actor #b2beb5 Administrador <<User>> as adm
'actor #36454f "Profissional de saúde" <<User>> as pf

(Seleciona os dados para emissão do relatório) as sder
(Seleciona o modelo a ser aplicado ao relatório) as smar
(Monta o relatório no formado escolhido e envia aos interessados) as mrfeei

adm --> sder
adm --> smar

sder --> sys
smar --> sys
sys --> mrfeei

@enduml